config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'
  resources :users

  get 'admin', to: 'admin#index'

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	attr_accessor :remember_token
	before_save :email_downcase
	validates :username, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
																		uniqueness: {case_sensitive: false}
	validates :password, presence: true, length: {minimum: 6}

	def User.new_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

	def remember
		self.remember_token = User.new_token
		update_attribute(:remember_digest, User.digest(remember_token))
	end

	def authenticated?(remember_token)
		return false if remember_digest.nil?
		BCrypt::Password.new(remember_digest).is_password?(remember_token)
	end

	def forget
		update_attribute(:remember_digest, nil)
	end

	private
	def email_downcase
		self.email = email.downcase
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	# before_action :authenticate
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	# before_action :authenticate

	include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		login user
      params[:session][:remember_me] == 1 ? remember(user) : forget(user)
  		redirect_to admin_path
  	else
  		flash[:error] = "Invalid E-mail or Password"
  		render 'new'
  	end
  end

  def destroy
  	logout if sign_in?
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      login @user
  		flash[:success] = 'Sign Up Successfully!'
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def login(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def current_user
		if (user_id = session[:user_id])
			@current_user ||= User.find_by(id: user_id)
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(cookies[:remember_token])
				login user
				@current_user = user
			end
		end
	end

	def sign_in?
		!current_user.nil?
	end

	def logout
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<% if sign_in? %>
	<%= link_to current_user.username, root_path %>
	<%= link_to 'Logout', logout_path, method: :delete %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato|Poppins&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/toastr.min.css"/>
    <script src="/assets/toastr.min.js"></script>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <script type="text/javascript">
        toastr.<%= key %>('<%= value%>!', '<%= key.capitalize %>')
      </script>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE HTML>
<html>
<head>
	<title>eBELL :: Login</title>
	<link href="/assets/loginstyle.css" rel="stylesheet" type="text/css"/>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<script src="/assets/jquery-1.11.1.min.js"></script>
</head>

<body style="padding: 3em 0;">
	<div id="header">
		<div id="header-content">
			<a href="<%= root_path %>"><img class="img-fulid" src="/assets/logo.png" alt="eBell"></a>
		</div>
	</div>
	<div class="wthree-dot">
		<div class="profile">
			<div class="wrap">
				<div class="wthree-grids">
					<div class="content-left">
						<div class="content-info">
							<h2>Brief History About Us</h2>
							<div class="slider">
								<div class="callbacks_container">
									<ul class="rslides callbacks callbacks1" id="slider4">
										<li>
											<div class="w3layouts-banner-info">
												<h3>Vivamus dui dolor</h3>
												<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean et placerat leo, non condimentum justo</p>
											</div>
										</li>
										<li>
											<div class="w3layouts-banner-info">
												<h3>Duis in nisl egestas</h3>
												<p>Suspendisse leo lacus, hendrerit consectetur scelerisque in, tempor sit amet tortor. Pellentesque rhoncus</p>
											</div>
										</li>
									</ul>
								</div>
								<div class="clear"> </div>
							</div>
							<div class="agileinfo-follow">
								<h4>Sign Up with</h4>
							</div>
							<div class="agileinfo-social-grids">
								<ul>
									<a href="#"><i class="fa fa-facebook"></i></a>
									<a href="#"><i class="fa fa-twitter"></i></a>
									<a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
								</ul>
							</div>
							<div class="agile-signin">
								<h4>Already have an account <%= link_to 'Sign In', login_path %></h4>
							</div>
						</div>
					</div>
					<div class="content-main">
						<div class="w3ls-subscribe">
							<h4>eBELL SignUp</h4>
							<%= form_for(@user) do |f| %>
								<%= f.text_field :username, class: 'form-control', placeholder: 'Username' %>
								<%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
								<%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
								<%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirm Password' %>
								<div style="float: right;">
									<%= f.submit 'Sign up' %>
								</div>								
							<% end %>
						</div>
					</div>
					<div class="clear"> </div>
				</div>
			</div>
		</div>
	</div>
	
	<script src="/assets/responsiveslides.min.js"></script>
	<script>
		$(function () {
			$("#slider4").responsiveSlides({
				auto: true,
				pager:true,
				nav:false,
				speed: 400,
				namespace: "callbacks",
				before: function () {
					$('.events').append("<li>before event fired.</li>");
				},
				after: function () {
					$('.events').append("<li>after event fired.</li>");
				}
			});
		});
	</script>
</body>
</html>